// File /Native/Engine/Event/InputConstant.h
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 - Present Pen-NineCat(PenNineCat) https://github.com/Pen-NineCat

#pragma once

namespace PenEngine
{
    enum class ModifyKey
    {
        None = 0,
        Shift = 1,
        Ctrl = 2,
        Alt = 4,
    };

    enum class MouseState
    {
        None = 0,
        RightRelease = 1,
        RightClick = 2,
        LeftRelease = 3,
        LeftClick = 4,
        MiddleRelease = 5,
        MiddleClick = 6,
        X1Release = 7,
        X1Click = 8,
        X2Release = 9,
        X2Click = 10,
    };

    enum class VKey
    {
        None = 0,
        LButton = 0x01,           // 鼠标左键
        RButton = 0x02,           // 鼠标右键
        Cancel = 0x03,            // 控制中断处理
        MiddleButton = 0x04,      // 鼠标中间按钮
        X1Button = 0x05,          // X1 鼠标按钮
        X2Button = 0x06,          // X2 鼠标按钮
        Backspace = 0x08,         // Backspace 键
        Tab = 0x09,               // Tab 键
        Clear = 0x0C,             // 清除键
        Return = 0x0D,            // 回车键
        Shift = 0x10,             // Shift 键
        Ctrl = 0x11,              // Ctrl 键
        Menu = 0x12,              // Alt 键
        Pause = 0x13,             // 暂停键
        CapsLock = 0x14,          // Caps Lock 键
        Kana = 0x15,              // IME 假名模式
        Hangul = 0x16,            // IME 朝鲜文模式
        IMEOn = 0x17,             // IME 开启
        Junja = 0x18,             // IME Junja 模式
        Final = 0x19,             // IME 最终模式
        Hanja = 0x1A,             // IME Hanja 模式
        Kanji = 0x1B,             // IME 汉字模式
        IMEOff = 0x1C,            // IME 关闭
        Escape = 0x1D,            // Esc 键
        Convert = 0x1C,           // IME 转换
        NonConvert = 0x1D,        // IME 非转换
        Accept = 0x1E,            // IME 接受
        ModeChange = 0x1F,        // IME 模式更改请求
        Space = 0x20,             // 空格键
        Prior = 0x21,             // Page Up 键
        Next = 0x22,              // Page Down 键
        End = 0x23,               // End 键
        Home = 0x24,              // Home 键
        Left = 0x25,              // 左方向键
        Up = 0x26,                // 上方向键
        Right = 0x27,             // 右方向键
        Down = 0x28,              // 下方向键
        Select = 0x29,            // 选择键
        Print = 0x2A,             // 打印键
        Execute = 0x2B,           // 执行键
        Snapshot = 0x2C,          // 打印屏幕键
        Insert = 0x2D,            // Insert 键
        Delete = 0x2E,            // Delete 键
        Help = 0x2F,              // 帮助键
        Key0 = 0x30,             // 0 键
        Key1 = 0x31,             // 1 键
        Key2 = 0x32,             // 2 键
        Key3 = 0x33,             // 3 键
        Key4 = 0x34,             // 4 键
        Key5 = 0x35,             // 5 键
        Key6 = 0x36,             // 6 键
        Key7 = 0x37,             // 7 键
        Key8 = 0x38,             // 8 键
        Key9 = 0x39,             // 9 键
        KeyA = 0x41,             // A 键
        KeyB = 0x42,             // B 键
        KeyC = 0x43,             // C 键
        KeyD = 0x44,             // D 键
        KeyE = 0x45,             // E 键
        KeyF = 0x46,             // F 键
        KeyG = 0x47,             // G 键
        KeyH = 0x48,             // H 键
        KeyI = 0x49,             // I 键
        KeyJ = 0x4A,             // J 键
        KeyK = 0x4B,             // K 键
        KeyL = 0x4C,             // L 键
        KeyM = 0x4D,             // M 键
        KeyN = 0x4E,             // N 键
        KeyO = 0x4F,             // O 键
        KeyP = 0x50,             // P 键
        KeyQ = 0x51,             // Q 键
        KeyR = 0x52,             // R 键
        KeyS = 0x53,             // S 键
        KeyT = 0x54,             // T 键
        KeyU = 0x55,             // U 键
        KeyV = 0x56,             // V 键
        KeyW = 0x57,             // W 键
        KeyX = 0x58,             // X 键
        KeyY = 0x59,             // Y 键
        KeyZ = 0x5A,             // Z 键
        LWin = 0x5B,              // 左 Windows 徽标键
        RWin = 0x5C,              // 右 Windows 徽标键
        Apps = 0x5D,              // 应用程序键
        Sleep = 0x5F,             // 计算机睡眠键
        NumPad0 = 0x60,           // 数字键盘 0 键
        NumPad1 = 0x61,           // 数字键盘 1 键
        NumPad2 = 0x62,           // 数字键盘 2 键
        NumPad3 = 0x63,           // 数字键盘 3 键
        NumPad4 = 0x64,           // 数字键盘 4 键
        NumPad5 = 0x65,           // 数字键盘 5 键
        NumPad6 = 0x66,           // 数字键盘 6 键
        NumPad7 = 0x67,           // 数字键盘 7 键
        NumPad8 = 0x68,           // 数字键盘 8 键
        NumPad9 = 0x69,           // 数字键盘 9 键
        Multiply = 0x6A,          // 乘号键
        Add = 0x6B,               // 加号键
        Separator = 0x6C,         // 分隔符键
        Subtract = 0x6D,          // 减号键
        Decimal = 0x6E,           // 小数点键
        Divide = 0x6F,            // 除号键
        F1 = 0x70,                // F1 键
        F2 = 0x71,                // F2 键
        F3 = 0x72,                // F3 键
        F4 = 0x73,                // F4 键
        F5 = 0x74,                // F5 键
        F6 = 0x75,                // F6 键
        F7 = 0x76,                // F7 键
        F8 = 0x77,                // F8 键
        F9 = 0x78,                // F9 键
        F10 = 0x79,               // F10 键
        F11 = 0x7A,               // F11 键
        F12 = 0x7B,               // F12 键
        F13 = 0x7C,               // F13 键
        F14 = 0x7D,               // F14 键
        F15 = 0x7E,               // F15 键
        F16 = 0x7F,               // F16 键
        F17 = 0x80,               // F17 键
        F18 = 0x81,               // F18 键
        F19 = 0x82,               // F19 键
        F20 = 0x83,               // F20 键
        F21 = 0x84,               // F21 键
        F22 = 0x85,               // F22 键
        F23 = 0x86,               // F23 键
        F24 = 0x87,               // F24 键
        NumLock = 0x90,           // Num Lock 键
        ScrollLock = 0x91,            // Scroll Lock 键
        LShift = 0xA0,            // 左 Shift 键
        RShift = 0xA1,            // 右 Shift 键
        LControl = 0xA2,          // 左 Ctrl 键
        RControl = 0xA3,          // 右 Ctrl 键
        LMenu = 0xA4,             // 左 Alt 键
        RMenu = 0xA5,             // 右 Alt 键
        BrowserBack = 0xA6,      // 浏览器后退键
        BrowserForward = 0xA7,   // 浏览器前进键
        BrowserRefresh = 0xA8,   // 浏览器刷新键
        BrowserStop = 0xA9,      // 浏览器停止键
        BrowserSearch = 0xAA,    // 浏览器搜索键
        BrowserFavorites = 0xAB, // 浏览器收藏夹键
        BrowserHome = 0xAC,      // 浏览器主页键
        VolumeMute = 0xAD,       // 音量静音键
        VolumeDown = 0xAE,       // 音量减小键
        VolumeUp = 0xAF,         // 音量增大键
        MediaNextTrack = 0xB0,  // 下一曲键
        MediaPrevTrack = 0xB1,  // 上一曲键
        MediaStop = 0xB2,        // 停止媒体键
        MediaPlayPause = 0xB3,  // 播放/暂停媒体键
        LaunchMail = 0xB4,       // 启动邮件键
        LaunchMediaSelect = 0xB5, // 选择媒体键
        LaunchApp1 = 0xB6,       // 启动应用程序 1 键
        LaunchApp2 = 0xB7,       // 启动应用程序 2 键
        OEM_1 = 0xBA,             // US ANSI 键盘: 分号和冒号键
        OEM_PLUS = 0xBB,          // 等号和加号键
        OEM_COMMA = 0xBC,         // 逗号和小于号键
        OEM_MINUS = 0xBD,         // 减号和下划线键
        OEM_PERIOD = 0xBE,        // 句号和大于号键
        OEM_2 = 0xBF,             // US ANSI 键盘: 斜杠和问号键
        OEM_3 = 0xC0,             // US ANSI 键盘: 反引号和波浪号键
        GamePadA = 0xC3,         // 游戏板 A 按钮
        GamePadB = 0xC4,         // 游戏板 B 按钮
        GamePadX = 0xC5,         // 游戏板 X 按钮
        GamePadY = 0xC6,         // 游戏板 Y 按钮
        GamePadRightShoulder = 0xC7, // 游戏板右肩按钮
        GamePadLeftShoulder = 0xC8,  // 游戏板左肩按钮
        GamePadLeftTrigger = 0xC9,   // 游戏板左触发器按钮
        GamePadRightTrigger = 0xCA,  // 游戏板右触发器按钮
        GamePadDPadUp = 0xCB,        // 游戏板方向键上
        GamePadDPadDown = 0xCC,      // 游戏板方向键下
        GamePadDPadLeft = 0xCD,      // 游戏板方向键左
        GamePadDPadRight = 0xCE,     // 游戏板方向键右
        GamePadMenu = 0xCF,           // 游戏板菜单/开始按钮
        GamePadView = 0xD0,           // 游戏板视图/后退按钮
        GamePadLeftThumbstickButton = 0xD1,  // 游戏板左摇杆按钮
        GamePadRightThumbstickButton = 0xD2, // 游戏板右摇杆按钮
        GamePadLeftThumbstickUp = 0xD3,      // 游戏板左摇杆上
        GamePadLeftThumbstickDown = 0xD4,    // 游戏板左摇杆下
        GamePadLeftThumbstickRight = 0xD5,   // 游戏板左摇杆右
        GamePadLeftThumbstickLeft = 0xD6,    // 游戏板左摇杆左
        GamePadRightThumbstickUp = 0xD7,     // 游戏板右摇杆上
        GamePadRightThumbstickDown = 0xD8,   // 游戏板右摇杆下
        GamePadRightThumbstickRight = 0xD9,  // 游戏板右摇杆右
        GamePadRightThumbstickLeft = 0xDA,   // 游戏板右摇杆左
        OEM_4 = 0xDB,             // US ANSI 键盘: 左方括号键
        OEM_5 = 0xDC,             // US ANSI 键盘: 反斜杠和管道键
        OEM_6 = 0xDD,             // US ANSI 键盘: 右方括号键
        OEM_7 = 0xDE,             // US ANSI 键盘: 单引号和双引号键
        OEM_8 = 0xDF,             // 加拿大 CSA 键盘: 右 Ctrl 键
        OEM_102 = 0xE2,           // 欧洲 ISO 键盘: 反斜杠和管道键
        ProcessKey = 0xE5,        // IME 处理键
        Packet = 0xE7,            // Unicode 字符输入键
        Attn = 0xF6,              // Attn 键
        CrSel = 0xF7,             // CrSel 键
        ExSel = 0xF8,             // ExSel 键
        EREOF = 0xF9,             // 擦除 EOF 键
        Play = 0xFA,              // 播放键
        Zoom = 0xFB,              // 缩放键
        NoName = 0xFC,            // 保留
        Pa1 = 0xFD,               // PA1 键
        OEM_CLEAR = 0xFE,         // 清除键
    };
}
